### ISSUE TITLE
Precip aggregation to PRMS scale: Area-weighted average, area-weighted sum, vs sum 

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb_gridmet_tools#12]
**Recap:**

8 gridmet variables were extracted for the drb. These gridmet metrics are daily timesteps since 1979 and available for each hru.

Since we are working with the PRMS segment network, we choose to match the PRMS segments with adjacent HRU polygons and aggregate the values of the Hrus to PRMS. 

For temp ('tmmx', 'tmmn'), radiation (srad), windspeed (vs), and humidity measurements (rmin, rmax, sph), the aggregation is done as a area-weighted average such that the size of the hru polygon influences the mean value tied to that segment. 

Our final gridmet variable pr, is accumulated precipitaiton (inch). Should the area of the hru affect the precip aggregation? We could compute: 

* area-weighted mean like the other variables - but this would not give a strong indication of the total amount of potential run off into the segment on a given day.  
* sum - but possible bias present for prms segments tied to many hrus.

**Example:**

Take for example, PRMS segment 886_1 (blue) which has two HRUs on each side of the segment: 

Day: 1885-09-09

![image](https://user-images.githubusercontent.com/36547359/159030683-81541d98-d776-4039-8254-f852900df484.png)

![image](https://user-images.githubusercontent.com/36547359/159030789-be3daceb-f9ce-4eb7-bade-f59917a7a454.png)

The area-weighted average gives us a value of ~0.1814 inch non-weighted mean =~ 0.185 inch) 

![image](https://user-images.githubusercontent.com/36547359/159031623-1aadb0c2-3670-47dd-aa1d-47954964fa07.png)
_(Note - i merged the hru geometry information to the aggregated table for this image)_. 

Meanwhile the basic sum of accumulated precip for 886_1 = ~0.37 inch. 

Please provide your preference on this @jds485 @jzwart

**Comment by jzwart** [comment]
The accumulated precipitation value from gridMET is total daily accumulation in depth units (inches), so the basic sum of accumulated precipitation across 2 HRUs contributing to one segment would be double counting the amount of precipitation fallen in a given day. For example, if it rained 1 inch everywhere in the DRB, segments with 2 HRUs will have 2 inches contributing while segments with 1 HRU will have 1 inch contributing and this is independent of total HRU area. 

If we want total amount of precipitation contributing to a given segment, then we'd first have to multiply the depth units by the area of the HRUs and _then_ sum the those values, resulting in volumetric units of precipitation. 

I'm fine with either summed volumetric units of precipitation or area-weighted mean of precipitation. I prefer area-weighted mean of precipitation because it's equivalent to other meteorological units (depth) and is equivalent information if we supply the models with total area of the HRUs contributing to the segments. 

e.g. 
```
# hru 1 and 2 contribute to the same segment 
hru_area_1 = 100 # units of m2 
hru_area_2 = 300 

hru_pr_1 = 0.05 # units of m 
hru_pr_2 = 0.03 

# basic sum; units of m 
hru_pr_1 + hru_pr_2
[1] 0.08

# area-weighted mean; units of m 
(hru_area_1*hru_pr_1 + hru_area_2*hru_pr_2) / (hru_area_1 + hru_area_2)
[1] 0.035

# total volumetric precipitation; units of m3 
hru_area_1*hru_pr_1 + hru_area_2*hru_pr_2
[1] 14 

# area-weighted mean x total HRU area is equivalent to total volumetric precipitation 

```

**Comment by jds485** [comment]
Thanks! I didn't realize the precip units were depth instead of volume. That makes sense to use area-weighted mean, then

**Comment by msleckman** [comment]
Alright, not changes to the output dataset in that case. Current gridmet dataset in IS project data folder in sharepoint (gridmet_drb_agg_v2.csv) is aggregated as **area-weighted mean** for all gridmet variables.

**Comment by jzwart** [comment]
Thanks @msleckman !
